ALTER TABLE CATEGORIES  ADD CONSTRAINT PK_CATEGORIES PRIMARY KEY (CODE_CATEGORIE) ;

ALTER TABLE CLIENTS ADD CONSTRAINT PK_CLIENTS PRIMARY KEY (CODE_CLIENT) ;
ALTER TABLE COMMANDES ADD CONSTRAINT PK_COMMANDES PRIMARY KEY (NO_COMMANDE) ;
ALTER TABLE DETAILS_COMMANDES ADD CONSTRAINT PK_DETAILS_COMMANDES PRIMARY KEY (NO_COMMANDE, REF_PRODUIT) ;
ALTER TABLE EMPLOYES ADD CONSTRAINT PK_EMPLOYES PRIMARY KEY (NO_EMPLOYE) ;
ALTER TABLE FOURNISSEURS ADD CONSTRAINT PK_FOURNISSEURS PRIMARY KEY (NO_FOURNISSEUR) ;
ALTER TABLE PRODUITS ADD CONSTRAINT PK_PRODUITS PRIMARY KEY (REF_PRODUIT) ;


ALTER TABLE COMMANDES ADD CONSTRAINT FK_COMMANDE_CLIENTS  
FOREIGN KEY (CODE_CLIENT) REFERENCES CLIENTS (CODE_CLIENT) ;

ALTER TABLE COMMANDES ADD CONSTRAINT FK_COMMANDE_EMPLOYES 
FOREIGN KEY (NO_EMPLOYE) REFERENCES EMPLOYES (NO_EMPLOYE) ;

ALTER TABLE DETAILS_COMMANDES ADD CONSTRAINT FK_DETAILS_COMMANDES_COMMANDES 
FOREIGN KEY (NO_COMMANDE) REFERENCES COMMANDES (NO_COMMANDE) ;

ALTER TABLE DETAILS_COMMANDES ADD CONSTRAINT FK_DETAILS_COMMANDES_PRODUITS
FOREIGN KEY (REF_PRODUIT) REFERENCES PRODUITS (REF_PRODUIT) ;

ALTER TABLE DETAILS_COMMANDES ADD CONSTRAINT FK_DETAILS_PRODUITS_PRODUITS 
FOREIGN KEY (REF_PRODUIT) REFERENCES PRODUITS (REF_PRODUIT)  ;

ALTER TABLE EMPLOYES ADD CONSTRAINT FK_EMPLOYES_EMPLOYES 
FOREIGN KEY (REND_COMPTE) REFERENCES EMPLOYES (NO_EMPLOYE)   ;

ALTER TABLE PRODUITS ADD CONSTRAINT FK_PRODUITS_CATEGORIE 
FOREIGN KEY (CODE_CATEGORIE) REFERENCES CATEGORIES (CODE_CATEGORIE) ;

ALTER TABLE PRODUITS ADD CONSTRAINT FK_PRODUITS_FOURNISEUR 
FOREIGN KEY (NO_FOURNISSEUR) REFERENCES FOURNISSEURS (NO_FOURNISSEUR) ;

