CREATE DATABASE LINK if_oracle01
   CONNECT TO fmacerouss IDENTIFIED BY mdporacle
   USING 'DB1'; 
   
drop public database link RYORI;

SELECT * 
FROM Ryori.clients@if_oracle01;

--IMPORT PRODUITS ET CONTRAINTE
CREATE TABLE Produits 
AS (SELECT * FROM Ryori.Produits@if_oracle01);
ALTER TABLE PRODUITS ADD CONSTRAINT PK_PRODUITS PRIMARY KEY (REF_PRODUIT) ;
ALTER TABLE PRODUITS ADD CONSTRAINT FK_PRODUITS_CATEGORIE 
FOREIGN KEY (CODE_CATEGORIE) REFERENCES CATEGORIES (CODE_CATEGORIE) ;

--IMPORT CATEGORIES ET CONTRAINTE
CREATE TABLE Categories 
AS (SELECT * FROM Ryori.Categories@if_oracle01);
ALTER TABLE CATEGORIES  ADD CONSTRAINT PK_CATEGORIES PRIMARY KEY (CODE_CATEGORIE) ;

SELECT distinct pays
FROM Ryori.clients@if_oracle01
ORDER BY pays ASC;

-- IMPORT CLIENTS ET CONTRAINTE
CREATE TABLE Clients_Europe_Sud 
AS (SELECT * 
    FROM Ryori.Clients@if_oracle01
    WHERE pays = 'Espagne'
      OR pays = 'France'
      OR pays = 'Portugal'
      OR pays = 'Italie' 
      OR pays = 'Espagne'
      );   
ALTER TABLE CLIENTS_EUROPE_SUD ADD CONSTRAINT PK_CLIENTS_EUS PRIMARY KEY (CODE_CLIENT) ;
 
-- IMPORT STOCK ET CONTRAINTE      
CREATE TABLE Stock_Europe_Sud 
AS (SELECT * 
    FROM Ryori.Stock@if_oracle01
    WHERE pays = 'Espagne'
      OR pays = 'France'
      OR pays = 'Portugal'
      OR pays = 'Italie' 
      OR pays = 'Espagne'
      );
ALTER TABLE STOCK_EUROPE_SUD  ADD CONSTRAINT PK_STOCK_EUS PRIMARY KEY (REF_PRODUIT, PAYS) ;
ALTER TABLE STOCK_EUROPE_SUD ADD CONSTRAINT FK_STOCK_PROD_EUS 
FOREIGN KEY (REF_PRODUIT) REFERENCES PRODUITS (REF_PRODUIT)  ;

--IMPORT COMMANDES ET CONTRAINTE
CREATE TABLE Commandes_Europe_Sud 
AS (SELECT * 
    FROM Ryori.Commandes@if_oracle01 Com
    WHERE EXISTS
      (SELECT *
       FROM Clients_Europe_Sud cl
       WHERE cl.Code_Client = Com.Code_Client
      )
);
ALTER TABLE COMMANDES_EUROPE_SUD ADD CONSTRAINT PK_COMMANDES_EUS PRIMARY KEY (NO_COMMANDE) ;
ALTER TABLE COMMANDES_EUROPE_SUD ADD CONSTRAINT FK_COMMANDE_CLIENTS_EUS  
FOREIGN KEY (CODE_CLIENT) REFERENCES CLIENTS_EUROPE_SUD (CODE_CLIENT) ;


--IMPORT DETAILS_COMMANDES ET CONTRAINTE
CREATE TABLE Details_Commandes_Europe_Sud 
AS (SELECT * 
    FROM Ryori.Details_Commandes@if_oracle01 DetCom
    WHERE EXISTS
      (SELECT *
       FROM Commandes_Europe_Sud comEU
       WHERE comEU.NO_COMMANDE = DetCom.NO_COMMANDE
      )
);
ALTER TABLE DETAILS_COMMANDES_EUROPE_SUD ADD CONSTRAINT PK_DETAILS_COMMANDES_EUS PRIMARY KEY (NO_COMMANDE, REF_PRODUIT) ;
ALTER TABLE DETAILS_COMMANDES_EUROPE_SUD ADD CONSTRAINT FK_DETAILS_COM_COM_EUS 
FOREIGN KEY (NO_COMMANDE) REFERENCES COMMANDES_EUROPE_SUD (NO_COMMANDE) ;
ALTER TABLE DETAILS_COMMANDES_EUROPE_SUD ADD CONSTRAINT FK_DETAILS_PROD_PROD_EUS 
FOREIGN KEY (REF_PRODUIT) REFERENCES PRODUITS (REF_PRODUIT)  ;

--DBLINK
CREATE DATABASE LINK Amerique
   CONNECT TO fmacerouss IDENTIFIED BY mdporacle
   USING 'DB4'; 

CREATE DATABASE LINK Europe_Nord
   CONNECT TO fmacerouss IDENTIFIED BY mdporacle
   USING 'DB2'; 

--View
CREATE VIEW Clients AS 
   SELECT *
   FROM pesotir.Clients_Amerique@Amerique
   UNION
   select *
   FROM gsarnette.Clients_Europe_Nord@Europe_Nord
   UNION
   SELECT *
   FROM fmacerouss.CLIENTS_EUROPE_SUD;
   
CREATE VIEW Produits AS 
   SELECT *
   FROM pesotir.produits_Amerique@Amerique
   UNION
   select *
   FROM gsarnette.produits_Europe_Nord@Europe_Nord
   UNION
   SELECT *
   FROM fmacerouss.PRODUITS;


--TRIGGER*
SELECT *
FROM GSARNETTE.Clients_Europe_Nord@Europe_Nord;
